.github/workflows/pr-build.yml
.github/workflows/seed-build.yml
install/friendly-filenames.json

Add build support for windows_amd64, windows_arm64 and android_arm64.

ci/feat(seed-build): add windows and android build

---

cmd/server/README.md
cmd/server/run.go
config/config.go

`fwmark` should be hex instead of decimal.

fix: should support hex fwmark

---

.github/workflows/build.yml
.github/workflows/daily-build.yml
.github/workflows/pr-build.yml
.github/workflows/seed-build.yml
.github/workflows/seed-release-build.yml

Enable `pre-actions` and `post-actions` stages in [build,pr-build,daily-build].
- ci(pr-build): enable check_run stages
- fix: inherit secrets from org_secrets
- feat: add telegram-creds for pre-actions
- feat(daily-build): enable pre-actions and post-actions stages
- feat(build): enable pre-actions and post-actions stages
- patch(seed-build): enable report status stage
- chore: use underscore notations for reusable workflow inputs
NA
https://github.com/juicity/juicity/actions/runs/5705680442

ci(build,pr-build,daily-build): enable check_run stages

---

cmd/client/README.md

As title.
- Update client/README.md.
Closes #41

docs: add authentication docs of http/socks5 listening

---

README.md
cmd/client/README.md
cmd/client/run.go
cmd/server/README.md
cmd/server/gen_certchain_hash.go
common/utils.go
config/config.go

Sometimes, we want to use a self-signed certificate without trusting it in the system. This PR implements `Certificate Pinning` to solve it.
- Support `juicity-server generate-certchain-hash [cert_file]`.
- Support the `pinned_certchain_sha256` config item.
Closes #34
Normal case:
Abnormal case (hash unmatched):

feat: support certificate pinning

---

go.mod
go.sum

Upgrade quic-go to v0.37.3.
- Upgrade soft-wind.
- Upgrade quic-go.

chore: upgrade quic-go to v0.37.3

---

.dockerignore
CODEOWNERS
Dockerfile

Refine OCI image build process followed by the containerization best practice.
- chore: add dockerignore
- ci: refine dockerfile
- optimize: cache deps layer
- ci: add git as build deps
- optimize: refine copy deps layer
- patch: remove bash (reduce os footprint)

ci/optimize: docker refinement

---

cmd/client/run.go
cmd/server/README.md
cmd/server/gen_certchain_hash.go
cmd/server/gen_link.go

For example:
```bash
> ./juicity-server generate-sharinglink -c /etc/juicity/server.json
juicity://00000000-0000-0000-0000-000000000000:mypassword@1.2.3.4:15333?congestion_control=bbr&pinned_certchain_sha256=5ykL73pOK7NAu92A48dCrFjDqDowdChUSmlpQzudmvc%3D&sni=download.microsoft.com
```
- feat(server): support cmd generate-sharinglink

feat(server): support cmd generate-sharelink

---

cmd/server/README.md
cmd/server/gen_link.go

In main branch version, `juicity-server generate-sharelink -c [config.json]` always generates `pinned_certchain_sha256` whether or not the cert is self-signed. This PR optimizes it.
- Generate `pinned_certchain_sha256` only if the cert is self-signed.
NA

optimize(generate-sharelink): judge whether really need to pin

---

server/server.go

If an unistream is opened but data is read slowly and even longer than 10 seconds, the auth timeout will not be triggered, which is abnormal.

fix: fail to trigger auth timeout in some cases

---

go.mod
go.sum

arm32 panics:
```
panic: unaligned 64-bit atomic operation
```
- Upgrade softwind. <https://github.com/daeuniverse/softwind/commit/387d19f00f24a6d23b72dd55ce316ac46427118b>
Closes #89

fix: panic: unaligned 64-bit atomic operation

---

cmd/client/README.md
cmd/server/README.md
go.mod
go.sum

<https://github.com/quic-go/quic-go/releases/tag/v0.38.0>

chore: bump quic-go to v0.38.0

---

cmd/server/README.md
cmd/server/run.go
config/config.go
go.mod
go.sum
server/forwarder.go
server/inflight.go
server/server.go
server/udp_endpoint.go

`Quic-in-quic` doesn't play well in the high loss network (loss rate greater than 15%).
This PR supports to utilize `Demultiplexing QUIC` to solve this problem. See <https://github.com/quic-go/quic-go/releases/tag/v0.38.0>. Specifically, when treating UDP traffic with a destination port of 443/8443/5201, use raw udp sockets (underlying transport) to send and receive packets.
Bump quic-go to v0.38.1
- Implement `Demultiplexing QUIC` (underlay) to transport 443/8443/5201 packets.
- Support server option `disable_outbound_udp443`.

optimize: use raw udp conn to solve quic in quic problem

---

go.mod
go.sum
server/server.go

- Revert #103 until MTU problem fixed with DPLPMTUD.
- Fix `disable_outbound_udp443` does not work.
Closes #106

fix: disable_outbound_udp443 not work and revert #103

---

Dockerfile

Docker image builds failed due to go version incompatibility:
```
=> ERROR [builder 5/7] RUN go mod download                                                                        2.6s
------
> [builder 5/7] RUN go mod download:
2.416 go: errors parsing go.mod:
2.416 /app/go.mod:3: invalid go version '1.21.0': must match format 1.23
------
Dockerfile:13
--------------------
11 |
12 |     COPY go.mod go.sum ./
13 | >>> RUN go mod download
14 |
15 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
```
- [] There's an entry in the CHANGELOGS
- resolved the issue by changing the builder image in Dockerfile from `golang:1.20-alpine` to `golang:1.21-alpine`
Closes #114

Fix docker image build failure

---

.github/workflows/seed-build.yml
.github/workflows/seed-release-build.yml
Makefile
cmd/client/cgo_check.go
cmd/client/cmd.go
cmd/client/run.go
cmd/internal/shared/version.go
cmd/server/cgo_check.go
cmd/server/cmd.go
cmd/server/run.go
config/config.go

As the user requested in #122, we added support to extend the default version of print info.
- feat(cmd): enhance version print
- patch: do not print empty val if env not exist
- ci(smoke_test): use version instead of --version
- refactor: retrieve cgo compilation var by specifying tag at build time
Closes #122 
In Go, we can check if the `CGO_ENABLED` environment variable is set during the _**build**_ process using _**build tags**_. The `CGO_ENABLED` environment variable determines whether or not cgo (the Go tool for working with C) is enabled. We can conditionally include or exclude code based on the value of this environment variable. 
In https://github.com/juicity/juicity/pull/123/commits/afd4d60df4dd73dcca4f76a7008fba9a6c792dda, we use the build tag `cgo` to specify that …

feat(cmd): enhance version print

---

.github/workflows/docker-publish.yml

Fixed docker CI did not start when workflow update, add linux/arm64 Docker image
- add linux/arm64 Docker image
https://github.com/EkkoG/juicity/actions/runs/6610538011

Fixed docker CI did not start when workflow update, add linux/arm64 Docker image

---

cmd/internal/shared/version.go

Add copy-right and license info to version cmd.
- feat(cmd/version): add copy right and license info
NA
```console
◆ juicity git:(extra-info) ❯❯❯ make                                                                                                                       23:12:37
CGO_ENABLED=0 go build -o juicity-server -trimpath \
-ldflags "-s -w -X github.com/juicity/juicity/config.Version=unstable-20231024.r117.9e449a0" \
./cmd/server
CGO_ENABLED=0 go build -o juicity-client -trimpath \
-ldflags "-s -w -X github.com/juicity/juicity/config.Version=unstable-20231024.r117.9e449a0" \
./cmd/client
◆ juicity git:(extra-info) ❯❯❯ ./juicity-server --version                                                                                                 23:12:40
juicity-server version …
```

feat(cmd/version): add copy right and license info

---

cmd/server/gen_link.go

`shadowrocket` needs `allow_insecure=1` if a self-signed cert is given.
- Add allow_insecure=1 when generate sharelink if a self-signed cert is given.

fix: add allow_insecore=1 when cert need to pin

---

go.mod
go.sum

1. Upgrade daeuniverse/outbound.
1. Support to forward to v2ray-plugin nodes.
1. Support UDP of shadowsocks + simple-obfs.

feat/chore: support to forward to v2ray-plugin nodes
