juicity/juicity

.pre-commit-config.yaml

- chore: add pre-commit-config
NA
NA

chore: add pre-commit-config

---

install/friendly-filenames.json

As the name suggests.
- ci/chore: add friendly-filenames
NA
NA

ci/chore: add friendly-filenames

---

.github/workflows/build.yml
.github/workflows/daily-build.yml
.github/workflows/pr-build.yml
.github/workflows/seed-build.yml

Introduce CI workflows tailored to various events.
- ci: add seed-build
- ci: add pr-build
- ci: add daily-build
- ci: add main build

ci: bootstrap workflows

---

.github/workflows/pr-build.yml
.github/workflows/seed-build.yml

Apply patches to `seed-build` downstream workflow.
- ci: remove geodata artifact download (not needed)
- ci: remove unnecessary flags
- fix: fix smoke test logic
- ci: fix artifact export
https://github.com/juicity/juicity/actions/runs/5698905365?pr=8

ci(seed-build): general refinement

---

README.md

Add badges to readme.
- docs(readme): add repo badges
NA
NA

docs(readme): add repo badges

---

README.md

Add stargazers plot to readme
- docs(readme): add stargazers over time
NA
NA

docs(readme): add stargazers over time

---

.github/workflows/seed-build.yml
install/friendly-filenames.json

Fix filename suffix problem on Windows.

ci/fix(seed-build): windows suffix

---

.github/workflows/seed-build.yml

Upgrade golang from v1.19 to v1.20.

chore(ci/seed-build): upgrade golang to v1.20

---

server/server.go

- hotfix: fix server instantiation
NA
NA

hotfix: fix server instantiation

---

README.md

Add daed client.
- Update README.md

docs(readme): add daed client as a new juicity client

---

.github/workflows/pr-build.yml
.github/workflows/seed-build.yml
.github/workflows/seed-release-build.yml
install/example-client.json
install/example-server.json

- Add install/example-{client,server}.json
- Package them in workflows.

chore: add example-{client,server}.json

---

.github/workflows/seed-release-build.yml
cmd/client/README.md
cmd/server/README.md

docs: refine README

---

.github/workflows/build.yml
.github/workflows/daily-build.yml

Apply some hotfixes to #32.
- hotfix: fix secret inputs missing issue
NA
NA

hotfix/ci(build): fix secret inputs missing issue

---

.github/workflows/build.yml
.github/workflows/daily-build.yml

Demise `post-actions` stage for main-build (not needed)
- ci(build): demise post-actions stage for main-build
NA
NA

ci(build): demise post-actions stage for main-build

---

.github/workflows/generate-changelogs.yml
CHANGELOGS.md

Add `generate-changelogs` workflow
- chore: add changelogs.md
- ci: add generate-changelogs workflow
NA
NA

ci: add generate-changelogs workflow

---

.github/PULL_REQUEST_TEMPLATE.md

chore(pr_template): fix typos

---

pkg/log/log_test.go
server/server.go

- fixture(mock): fix syntax error in log_test.go
- fix(server): add error handling for handleClose
NA
NA

patch(server): add error handling for connClose

---

server/server.go

Add support to log source origin metadata.
- feat(sever): log source origin metadata
Closes #28

feat(sever): log source origin metadata

---

cmd/server/README.md

Link to https://github.com/juicity/juicity/issues/63
- docs(server): add UUID Generator section
Closes #63 
NA

docs(server): add UUID Generator section

---

Dockerfile

ci: add Dockerfile

---

.github/PULL_REQUEST_TEMPLATE.md

Update pr_template section headers

chore(pr_template): update pr_template section headers

---

README.md
docs/spec.md

In order to help more developers implement juicity and more users understand the specification of juicity, this PR adds `spec.md` to agree on the content and implementation of the protocol.
Closes #71

docs: add protocol spec

---

docs/spec.md
docs/spec_en.md

docs(spec): add English version specification

---

README.md
docs/spec.md
docs/spec_en.md

docs: add lang switch for spec.md

---

go.mod
go.sum

chore: upgrade quic-go to v0.37.6

---

go.mod
go.sum

See https://github.com/quinn-rs/quinn/pull/1637
- This PR upgrade go mod softwind.

chore: fix IsGSOError judgement

---

.github/workflows/docker-publish.yml

Make deploy juicity server easier.
- Add docker CI
no
https://github.com/EkkoG/juicity/pkgs/container/juicity/139716504?tag=v0.3.1
https://github.com/EkkoG/juicity/pkgs/container/juicity/139709638?tag=main

Add docker CI

---

.github/workflows/docker-publish.yml

- ci(docker-publish): limit workflow triggers
NA
Not applicable.

ci(docker-publish): limit workflow triggers

---

cmd/server/README.md

Describe how to deploy server with docker.
no need

Add docs for docker image usage

---

cmd/server/README.md

correct “—” to “-” in docker run
docker run error
- docker run correct
Closes #_none

Update README.md in docker run

---

cmd/client/run.go

See https://github.com/daeuniverse/dae/pull/391.

fix: disable gso on client by default

---

.github/workflows/docker-publish.yml
.github/workflows/lint.yml
.github/workflows/pr-build.yml
.github/workflows/seed-build.yml
.github/workflows/seed-release-build.yml

ci: update checkout and setup-go to latest
